export const VOICE_LINE = {
  1: 'Yes',
  2: 'No',
  3: 'Food, please 請給我食物',
  4: 'Wood, please 請給我木材',
  5: 'Gold, PLease 請給我黃金',
  6: 'Stone, please 請給我石頭',
  7: 'Ahh 啊～',
  8: 'All hail, king of the losers! 嗨，肉腳，你們好啊！',
  9: 'Oooh 噢',
  10: 'Back to Age 1 滾回世紀帝國 I 去',
  11: 'Herb laugh 奸笑聲',
  12: 'Ah! being rushed. 我快招架不住了',
  13: 'Sure, blame it on your ISP. 去怪你的網路公司',
  14: 'Start the game already! 遊戲開始了',
  15: 'Dont point that thing at me! 別用那個指著我',
  16: 'Enemy Sighted 發現敵人',
  17: 'It is good to be the king. 登上王位的感覺真好',
  18: 'Monk! I need a monk! 我還少個僧侶',
  19: 'Long Time No Siege 有一陣子沒交手囉',
  20: 'My granny could scrap better than that. 連我阿媽都比你行',
  21: 'Nice Town I’ll Take It 好地方，我要定了',
  22: 'Quit Touchin 別再打我了',
  23: 'Raiding Party 大夥進攻囉',
  24: 'Dadgum 真衰！',
  25: 'Smite Me 你敢就來啊',
  26: 'The wonder, the wonder, the... no! 糟了，是世界奇觀！',
  27: 'You play 2 hours 你玩這麼久才玩這樣',
  28: 'You Should See the Other Guy 還有人比你更慘',
  29: 'Roggan 肉腳',
  30: 'Wololo 歡呼聲',
  31: 'Attack an Enemy Now 馬上攻擊一個敵人 !!',
  32: 'Cease Creating Extra Villagers 停止生產額外的村民',
  33: 'Create Extra Villagers 生產額外的村民',
  34: 'Build a Navy 建立一隻海軍',
  35: 'Stop Building a Navy 停止建立海軍',
  36: 'Wait for My Signal to Attack 等我的信號進行攻擊 !!',
  37: 'Build a Wonder 建立世界奇觀吧 !!',
  38: 'Give Me Your Extra Resources 給我你多的資源吧',
  39: 'Ally 同盟',
  40: 'Enemy 敵對',
  41: 'Neutral 中立',
  42: 'What Age Are You In 你現在是什麼時期 ?',
};
